stages:
  - lint

cache:
  key:
    files:
      - package-lock.json #При изменения в этом файле будет создаваться заново кеш
  paths:
    - apps/main/node_modules #Какой путь кешировать

before_script: # Надо как то использовать кеш
  - cd apps/main
  - npm ci --cache node_modules --prefer-offline

eslint:
  image: node:14.17.0-alpine
  stage: lint
  script:
    - cd apps/main
    - npm install
    - npm run linter