name: eslint #Название джобы, оно будет отображено в списке на гитхабе

on: #Правила для работы workflow
  push: #Когда идёт новый пуш в ветку master
    branches: [master]
  pull_request: #Когда добавляется pull_request в ветку master
    branches: [master]

jobs:
  eslint: #Название джобы
    container:
      image: node:14.17.0-alpine #Окружение. Имя докер образа
    steps: #Шаги
      - uses: actions/checkout@v2 #Какой гитхаб экшен использовать      
      - name: Checkout directory
        run: cd apps/main
      - name: Install Dependencies
        run: npm install
      - name: Lint source code with eslint
        run: npm run linter
